title: <p align="center"> Vidushi Gangwar </p>
logo: /assets/img/1608160154037.jpg

description:
  <p align="center">
  <a href="https://github.com/vidushiga">GitHub</a>
  
  <br>   
  I am working as a Data Engineer and have 5.7 years of experience in IT industry.
  <br>
  </p>



theme: jekyll-theme-minimal
